### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by testsoftuvo** [gsuitedevs/php-samples#11]
Uncaught InvalidArgumentException: file does not exist in /var/www/html/solveapi/google-drive/vendor/google/apiclient/src/Google/Client.php:859

**Comment by erickoledadevrel** [comment]
This error indicates that it can't find the `credentials.json` file, did you move it into the same directory as your PHP script?

**Comment by mrgyf1** [comment]
@erickoledadevrel i have this problem too. I dont touch any files inside `vendor`

**Comment by erickoledadevrel** [comment]
In Step 1 the instructions include:

- Download the configuration file.
- Move the downloaded file to your working directory.

Did you do that?

**Comment by mrgyf1** [comment]
@erickoledadevrel oh, sorry its my fault! Now i did it but become a new error... `missing the required redirect URI`. I trying to use it on my local machine with OpenServer

**Comment by andriy159** [comment]
My server work in Ukraine. Maybe time not correctly. Bad i changed to NY. Result is bad.

If run programm with shs "php quickstart.php":

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/tviyuspi/vesilla.com.ua/test/quickstart.php on line 4
2018-08-05T19:41:25+00:00<br><br>

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/tviyuspi/vesilla.com.ua/test/quickstart.php on line 69

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/tviyuspi/vesilla.com.ua/test/vendor/google/auth/src/Cache/Item.php:129
Stack trace:
#0 /home/tviyuspi/vesilla.com.ua/test/vendor/google/auth/src/Cache/Item.php(129): DateTime->__construct('now + 1500 seco...')
#1 /home/tviyuspi/vesilla.com.ua/test/vendor/google/auth/src/CacheTrait.php(61): Google\Auth\Cache\Item->expiresAfter(1500)
#2 /home/tviyuspi/vesilla.com.ua/test/vendor/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php(171): Google\Auth\Middleware\ScopedAccessTokenMiddleware->setCachedValue('https://www.goo...', 'ya29.GlsOBmddDA...')
#3 /home/t in /home/tviyuspi/vesilla.com.ua/test/vendor/google/auth/src/Cache/Item.php on line 129
--------------------------------------------------------------------------------

If run other programm for Web+php (Google API Client Libraries PHP (Beta)):

Fatal error: Uncaught exception 'Google_Service_Exception' with message '{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } } ' in /home/tviyuspi/vesilla.com.ua/test/vendor/google/apiclient/src/Google/Http/REST.php:131 Stack trace: #0 /home/tviyuspi/vesilla.com.ua/test/vendor/google/apiclient/src/Google/Http/REST.php(107): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 /home/tviyuspi/vesilla.com.ua/test/vendor/google/apiclient/src/Google/Task/Runner.php(176): call_user_func_array(Array, Array) #3 /home/tviyuspi/vesilla.com.ua/test/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run() #4 /home/tviyuspi/v in /home/tviyuspi/vesilla.com.ua/test/vendor/google/apiclient/src/Google/Http/REST.php on line 131

**Comment by erickoledadevrel** [comment]
I'm not sure where that error is coming from, as I don't see it in the source code. Did you download the `credentials.json` file from the button in the quickstart instructions?

**Comment by erickoledadevrel** [comment]
Closing due to inactivity.
