### ISSUE TITLE
missing the required redirect URI

### ISSUE THREAD

**Issue by omerkhanjadoon** [gsuitedevs/php-samples#22]
i am getting the following error when i try to run quick.php (which is named as quickstart in google drive api docs) i have copy paste the exact code but getting the error when i run it from my command line

Error:
```
PHP Fatal error:  Uncaught InvalidArgumentException: missing the required redirect URI in C:\xampp\htdocs\dnew\vendor\google\auth\src\OAuth2.php:650
Stack trace:
#0 C:\xampp\htdocs\dnew\vendor\google\apiclient\src\Google\Client.php(339): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 C:\xampp\htdocs\dnew\quick.php(26): Google_Client->createAuthUrl()
#2 C:\xampp\htdocs\dnew\quick.php(58): getClient()
#3 {main}
  thrown in C:\xampp\htdocs\dnew\vendor\google\auth\src\OAuth2.php on line 650

Fatal error: Uncaught InvalidArgumentException: missing the required redirect URI in C:\xampp\htdocs\dnew\vendor\google\auth\src\OAuth2.php:650
Stack trace:
#0 C:\xampp\htdocs\dnew\vendor\google\apiclient\src\Google\Client.php(339): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 C:\xampp\htdocs\dnew\quick.php(26): Google_Client->createAuthUrl()
#2 C:\xampp\htdocs\dnew\quick.php(58): getClient()
#3 {main}
  thrown in C:\xampp\htdocs\dnew\vendor\google\auth\src\OAuth2.php on line 650
```

 Specifications

  - PHP version (`php -v-7.2.1`):
  - OS (Windows):

**Comment by uday-savitr** [comment]
I am getting the following error

any help appreciated.
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle in C:\wamp64\www\gdsample\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by erickoledadevrel** [comment]
Closing due to inactivity.

**Comment by paulcanning** [comment]
I have this same issue.

I have a credentials.json, but it does not has an 'installed' key in it. Also, I'm unsure if my json file is made correctly.

**Comment by erickoledadevrel** [comment]
Did you use the button on the quickstart page? It should ensure the correct settings are used.

**Comment by inside83** [comment]
I used type 'Web browser' and got an error

`PHP Fatal error:  Uncaught InvalidArgumentException: missing the required redirect URI in /root/vendor/google/auth/src/OAuth2.php:675`

https://developers.google.com/gmail/api/quickstart/php#troubleshooting says "This code requires an OAuth client ID of type Other" but 'Other' isn't offered as an option in the dropdown menu.
![image](https://user-images.githubusercontent.com/10822610/93792515-e85b8680-fc35-11ea-97bd-0007cdb99620.png)

**Comment by timcamps** [comment]
> I used type 'Web browser' and got an error
> 
> `PHP Fatal error: Uncaught InvalidArgumentException: missing the required redirect URI in /root/vendor/google/auth/src/OAuth2.php:675`
> 
> https://developers.google.com/gmail/api/quickstart/php#troubleshooting says "This code requires an OAuth client ID of type Other" but 'Other' isn't offered as an option in the dropdown menu.
> ![image](https://user-images.githubusercontent.com/10822610/93792515-e85b8680-fc35-11ea-97bd-0007cdb99620.png)

Make sure you have added the Redirect URI in your Client-ID:
![image](https://user-images.githubusercontent.com/1378077/100138771-ce852c80-2e8e-11eb-8f3d-6e39e6cdd547.png)

Also don't forget to download and replace the credentials.json file after you have made any changes:
![image](https://user-images.githubusercontent.com/1378077/100138851-e361c000-2e8e-11eb-9d75-4a3cc1631958.png)

**Comment by okellojohnsilas** [comment]
> > I used type 'Web browser' and got an error
> > `PHP Fatal error: Uncaught InvalidArgumentException: missing the required redirect URI in /root/vendor/google/auth/src/OAuth2.php:675`
> > https://developers.google.com/gmail/api/quickstart/php#troubleshooting says "This code requires an OAuth client ID of type Other" but 'Other' isn't offered as an option in the dropdown menu.
> > ![image](https://user-images.githubusercontent.com/10822610/93792515-e85b8680-fc35-11ea-97bd-0007cdb99620.png)
> 
> Make sure you have added the Redirect URI in your Client-ID: ![image](https://user-images.githubusercontent.com/1378077/100138771-ce852c80-2e8e-11eb-8f3d-6e39e6cdd547.png)
> 
> Also don't forget to download and replace the credentials.json file after you have made any changes: ![image](https://user-images.githubusercontent.com/1378077/100138851-e361c000-2e8e-11eb-9d75-4a3cc1631958.png)

This was very helpful.
Thanks a lot for this
